= MIDO SVG
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: mido-svg
:repository: MIDO-SVG

image:https://github.com/{gitHubUserName}/{repository}/workflows/Maven%20verify/badge.svg["Build Status", link="https://github.com/{gitHubUserName}/{repository}/actions"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in https://dauphine.psl.eu/en/training/bachelors-degrees/organizational-computer-science/bachelors3-business-informatics/program[MIAGE L3 Alternance]).

The code is hereby published under the https://github.com/oliviercailloux/{repository}/blob/master/LICENSE[MIT License], with their permission.

See the https://github.com/oliviercailloux/{repository}/blob/master/Doc/README.adoc[doc].

== Original description (to be translated)
L’objectif premier de ce projet est de créer une bibliothèque qui permet à un utilisateur de créer un dessin (au format SVG) représentant au moyen d’un arbre, les formations offertes dans le département MIDO. Il est aussi possible d’afficher les détails des formations, les enseignants, etc. L’idée est de généraliser et dynamiser la bibliothèque afin qu’elle puisse être utilisée à une plus grande échelle, ce en récupérant les informations sur le site de l’université.

Our main focus will be to use Fake Data as a start. We will make sure that we are able to programatically an SVG from the command line.