= MIDO SVG
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: mido-svg
:repository: MIDO-SVG

image:https://github.com/{gitHubUserName}/{repository}/workflows/Maven%20CI/badge.svg["Build Status", link="https://github.com/{gitHubUserName}/{repository}/actions"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in https://dauphine.psl.eu/formations/licences/informatique-des-organisations/l3-methodes-informatiques-appliquees-pour-la-gestion-des-entreprises[L3 MIAGE Alternance]).

The code is hereby published under the MIT License, with the permission of the contributors.

The project documentation is link:Doc/README.adoc[here].

== Objectif du projet
 
L’objectif premier de ce projet est de créer une bibliothèque qui permet à un utilisateur de créer un dessin (au format SVG) représentant au moyen d’un arbre, les formations offertes dans le département MIDO. Il est aussi possible d’afficher les détails des formations, les enseignants, etc. L’idée est de généraliser et dynamiser la bibliothèque afin qu’elle puisse être utilisée à une plus grande échelle, ce en récupérant les informations sur le site de l’université.

== Evolution Prévue (objectif à long terme)

Après avoir pris connaissance de l’existant, nous nous sommes aperçus que les évolutions à concevoir se portent essentiellement sur :

[square]
* La récupérationd de la base de données Dauphine
* La génération d'un fichier SVG fonctionnel
* L’esthétique GUI, aujourd’hui les différents formulaires sont incomplets et non responsive.
* Fichier tags, à ce jour la gestion des tags est static.
* La liste des utilisateurs habilités, dans notre application, nous constatons que seuls un certain nombre d’user est habilité à utiliser l’application. (ocailloux, ikram, cocolollipop, romain, jules)
