= Diagram Documentation File

== General
=== MIDO-SVG Diagram

image::../Doc/Diagrams/MIDO-SVG_General.svg[MIDO-SVG Diagram]

This diagram aim to represent an overview on our application.
 `Controller` package is no longer useful to us and will therefore be deleted in the next java iteration.

You can see the details of all these packages just below

== University

=== University Class Diagram 

image::../Doc/Diagrams/UniversityClassDiagram.svg[University Class Diagram]

The `Department` class represents the different Departments of the university (MIDO, LSO ...)
The `Formation` class is abstract, which will allow us to create other types of training with the same "default data" (a title, a grade ...)

The `UniversityClassDiagram` diagram allows you to view the different links between the classes in this package.
 
This package seems complete and functional to us, so we do not anticipate any major developments on this part of the project. However, additions of methods or attribute can be made if necessary to allow another evolution.

PS : We do not proceed to the suppression of Master et Licence and the attribut posX eand posY class, because it needed to draw the SVG file

== View

=== GUI Use Case Diagram 

image::../Doc/Diagrams/GUIUseCaseDiagram.svg[GUI Use Case Diagram]

The "GUI" aspect of the project is coded in the `view` package.
We observe that Mac user and Windows user didn't see the same thing. Windows user saw a unesthetic GUI form.
At this point of the project, there is no specific main class to run.
If we run the GUISVGLoginForm, the final user is able to log in (if the final user name is known by the application, coded in "model" database class.
On the other hand, if the programmer run another class, the name user is by default "ocailloux".
The big change here is to allow a user to acces to home page without the login process, a default value to "User"

The tag is saved in an xml file in `src/main/resources/tags/`

This is what we are planned to do :

[square]
* Saved the user preferences in a xml file and reuse it in a further launch application
* Be able to save courses preferences 
* Be able to access to the formation site by clicking on it


== Paper

=== Paper Class Diagram 

image::../Doc/Diagrams/PaperClassDiagram.svg[Paper Class Diagram]
 
The https://github.com/marcellinodour/MIDO-SVG/blob/master/Doc/Diagrams/PaperClassDiagram.svg[Paper Class Diagram] allows you to visualize the different links between the classes of this package.


== XML

=== XML Class Diagram 

image::../Doc/Diagrams/XMLClassDiagram.svg[XML Class Diagram]

The `xml` package enables us to generate tags and therefore make the link with the subjects.
Each tag has a name and a list of subjects.
The TagStore class allows you to store several tags.
In the future, we want to be able to choose the courses by tags. 

The `XMLMain` class (in the xml-to-java package) is used to retrieve an XML file and extract the data (name, first name, address, etc.) to store it in a hash table. Afterwards, this hash table will be used to fill the tags. 

== ROF Database

=== ROF  Dauphine Class Diagram 

image::../Doc/Diagrams/ROFDauphineClassDiagram.svg[ROF Dauphine Class Diagram]

This diagram aim to represent the structure of Dauphine's ROF database.

You can refer to https://github.com/marcellinodour/MIDO-SVG/blob/master/Doc/ROFDauphineDoc.adoc[this documentation] in order to better understand it. 

== Database

=== ROF Class Diagram 

image::../Doc/Diagrams/ROFClassDiagram.svg[ROF Class Diagram]

This diagram contains the classes that would be useful to retrieve the data directly from ROF. 

First of all, we need the `QueriesHelper` class to login into ROF. This class uses the files API_password.txt and WSDL_access.txt which are at the root of our project. (Be careful to not push this 2 files on GitHub !!)

Secondly, `Querier` class enables us to get the mentions, programs, courses and orgUnit from ROF. These are objects specific to ROF (see the diagram above). 
However, we need to transform these objects into `University` objects that we use in our project: Licence, Master, Teacher, Subject...

Therefore, in the `RofDatabase` class, after login into ROF and fetching the data from ROF, we create new `University` objects and fill their attributes with contents from ROF.


== SVG

=== SVG Class Diagram

image::../Doc/Diagrams/SVGClassDiagram.svg[SVG Class Diagram]

This diagram models the `svg-generator package`. It represents an overview of drawing an SVG process: the classes involved and the methods.
However, the process is much detailed in the SVG Sequence Diagram. 

=== SVG Sequence Diagram 

image::../Doc/Diagrams/SequenceSVG.svg[SVG Sequence Diagram]

This diagram represents the way a SVG image is generated by using the `View` package 

There is another way to generate the SVG image by using the `ControllerSVG` class in the `controller` package that makes the SVG image more responsive (according to the default settings)

