=== ROF  Dauphine Class Diagram 

image::../Doc/Diagrams/ROFDauphineClassDiagram.svg[ROF Dauphine Class Diagram]

OrgUnit is a table that regroup the major departments in Dauphine University (MIDO, LSO...). Each row of the table contains 
	** a label under this form `FRUAI0750736TOU******`. This label is the OrgUnitId which is the key that we can use as a predicate for the `Querier` class' methods.
	** details which is an URL to this row of OrgUnit
	** content which regroup the OrgUnitId, OrgUnitCode, OrgUnitName, admissionDescription and contact data.
	

As we can see in the diagram, OrgUnit does not point to any other table. That means there is no link between the MIDO department and the MIDO formations. 
If only in OrgUnit content, there was a list, let's name it refMentions, that contains a reference to all MIDO formations, it would be much easier to fetch all the informations that we need just by recovering the MIDO department key which is ``FRUAI0750736TOU0755233F``.



Small tip: In order to read the ROF database content, we use `codebeautify.org/jsonviewer`. By just copy/paste the content into this tool, you'll be able to have a more organized structure in which you can venture more comfortably. 