= README BACK UP (2020)

== Objectif du projet
 
L’objectif premier de ce projet est de créer une bibliothèque qui permet à un utilisateur de créer un dessin (au format SVG) représentant au moyen d’un arbre, les formations offertes dans le département MIDO. Il est aussi possible d’afficher les détails des formations, les enseignants, etc. L’idée est de généraliser et dynamiser la bibliothèque afin qu’elle puisse être utilisée à une plus grande échelle, ce en récupérant les informations sur le site de l’université.

== Notre solution

=== Les fonctionnalités (au 15.03.2020)
* Une interface graphique qui permettent de générer un fichier SVG, selon les critères de l’utilisateur.(Ikram)
* Une bibliothèque permettant de générer un fichier SVG mais sans passer par l’interface graphique (un exemple d’utilisation se trouve dans la classe ControllerSVG) (Caroline, Jules, Ikram, Romain)
* Une interface graphique qui permettent de générer une liste de mots clés (tags) pour des matières.
* Génération d’un SVG avec données statiques : voir dessin à la main, se concentrer sur partie Informatique des Organisations, dessin à partir d’une liste de cours en mémoire.
* Pouvoir ajouter les responsables aux parcours au dessin.
* Pouvoir ajouter les enseignants responsables de chaque cours au dessin.
* Différents types d’informations peuvent être colorées différemment.
* Récupérer les données depuis le web.
* Liens sur les parcours renvoient au programme des cours.
* Graphique équivalent pour la licence.
* Paramètres : licence seulement, master seulement
* Choix du format : A3 ou A4 ou autres dimensions que l’utilisateur choisit.
* Entrée et affichage de prérequis entre cours.
* Mots clés sur cours. Utilisateur peut associer des mots-clés aux cours via interface graphique.
* Mots clés enregistrés dans un fichier.
* Lecture des mots clés depuis un fichier.

=== Evolution envisagée

* L’esthétique GUI, aujourd’hui les différents formulaires sont incomplets et non responsive. Objectif : Correction d’affichage
* L'utilisateur doit être capable de saisir ses préférences (qui peuvent aussi être les cours suivis). Ces préférences peuvent être enregistrées pour les prochaines relances de l'application.
* La récupération base de données, les données utilisées à ce jour sont saisie “en dur”. Objectif : Récupération des données DSI
* La génération de l’image SVG, le rendu n’est pas satisfaisant. Objectif : Obtenir un graphe visible et qui pointe vers les pages des formations.
* Fichier tags, à ce jour la gestion des tags est static. Objectif : gestion des tags en dynamique
* La liste des utilisateurs habilités, dans notre application, nous constatons que seuls un certain nombre d’user est habilité à utiliser l’application. (ocailloux, ikram, cocolollipop, romain, jules). Objectif : Habilitation dynamique

=== L’architecture

On a séparé nos classes en 9 packages  en ayant pris soin de respecter une architecture MVC (Model View Controller):
 
* controller : Permet de générer un fichier XML qui permet de faire le lien entre des tags et des matières.
* jUnit : Contient les tests unitaires réalisés.
* model : Contient la base de données, avec tous les objets créés ou récupérable par XML.
* paper : Permet de définir la taille du canevas , Il prend 2 formes standard, connues (A3 et A4) et une forme libre (“Other”). Le pattern factory permet cette gestion.
* svg_generator : Contient les classes permettant de générer le SVG:
** ResponsiveSVG: permet de placer les informations au bon endroit sur le dessin en fonction du papier
** DrawSVGGen: dessine les formes (les traits, les flèches,les rectangles ..) et dessine les informations ( les formations, les enseignants ..)
** settings: précise les paramètres d’affichage .
* university.components : Ce package contient tous les éléments permettant de “former” une université : Une formation(Formation.java), un professeur(Teacher.java), une matière (Subject.java).
* view : Contient les interfaces graphiques qui se présente en deux parties principales : la gestion des tags , et la génération du SVG.
Ce package contient :
** Gestion des tags : cette interface nous permet d’ajouter ou supprimer des tags
** Génération du SVG : cette interface nous permet de choisir les paramètres d’affichage et dessiner le SVG
 
* xml_to_java : Permet de rappatrier le fichier XML que vous nous avez donné, https://raw.githubusercontent.com/oliviercailloux/projets/master/Voeux/OF_MEA5STI.xml, puis d’extraire les données du XML (nom, prenom, adresse mail, etc…)
* xml.jaxb.model : Permet de générer les tags, et faire le lien avec les matières
 
=== Technologies utilisées
 
- On a mis en place un projet Maven, hébergé sur Github
- On a mis en place Travis pour tester notre code source
- On a utilisé SWT pour générer les interfaces graphiques
- On a utilisé JAXB pour faire le lien entre tag et matières
- Pour récupérer les données depuis le fichier XML sur Internet, on a utilisé la classe URL puis le parser DOM du JDK.
- Pour générer les SVG, on a utilisé Batik
- Pour les loggers, on a utilisé SLF4J
